# Generated by Django 4.1.4 on 2022-12-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0002_alter_data_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=100),
        ),
    ]
