# Generated by Django 4.1.4 on 2022-12-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0004_alter_data_amount_alter_data_dateandtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=100),
        ),
    ]
